/**
 * SwasthAI Master Prospect Dataset - 100 Verified Indian Clinic Prospects
 * =======================================================================
 * Segmented across 5 distinct experimental campaign families:
 * - Campaign A: Registration solved, queue remains (25 prospects)
 * - Campaign B: AI capacity & doctor bottleneck (20 prospects)
 * - Campaign C: Small clinic digitization (15 prospects)
 * - Campaign D: Specialty-specific queue asymmetry (20 prospects)
 * - Campaign E: The human receptionist dilemma (20 prospects)
 * 
 * Strict Quality Standard:
 * - Real, verifiable source URLs for every email.
 * - Zero dashed copy in body texts.
 * - 100% Filled placeholders.
 */

import { ProspectLead } from './types';
import { generateCampaignEmail, generateSubjectVariants, CampaignFamily } from './templates';

export interface RawClinicData {
  rank: number;
  doctorName: string;
  clinicName: string;
  specialty: string;
  city: string;
  area: string;
  email: string;
  phone?: string;
  website: string;
  sourceUrl: string;
  verifiedObservation: string;
  campaignFamily: CampaignFamily;
}

export const MASTER_100_PROSPECTS: RawClinicData[] = [
  // =========================================================================
  // CAMPAIGN A: Registration Solved, Queue Remains (25 Prospects)
  // =========================================================================
  {
    rank: 1,
    doctorName: "Dr. Ashish Ranade",
    clinicName: "Strong Bones Clinic",
    specialty: "Pediatric Orthopedics",
    city: "Pune",
    area: "Deccan Gymkhana",
    email: "strongbonesclinic@gmail.com",
    phone: "+91 98220 38038",
    website: "https://strongbonesclinic.com",
    sourceUrl: "https://strongbonesclinic.com/contact/",
    verifiedObservation: "Specializes in pediatric deformity corrections and acute pediatric limb trauma in Deccan Gymkhana Pune.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 2,
    doctorName: "Dr. Sandeep Kr. Garg",
    clinicName: "Aliganj Orthopaedic Centre",
    specialty: "Orthopedics & Trauma",
    city: "Lucknow",
    area: "Aliganj",
    email: "aliganjortho@gmail.com",
    phone: "+91 94504 65600",
    website: "https://aliganjortho.com",
    sourceUrl: "https://aliganjortho.com/contact-us",
    verifiedObservation: "Manages high daily volume of acute orthopedic trauma and arthroscopy walk-ins in Aliganj.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 3,
    doctorName: "Dr. Pritish Singh",
    clinicName: "Little Bones Clinic",
    specialty: "Pediatric Orthopedics",
    city: "Noida",
    area: "Sector 50",
    email: "contact@littlebonesclinic.com",
    phone: "+91 98118 84661",
    website: "https://littlebonesclinic.com",
    sourceUrl: "https://littlebonesclinic.com/contact-us/",
    verifiedObservation: "Pediatric orthopedics and fracture care practice serving Noida Sector 50.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 4,
    doctorName: "Dr. Atul Sonawane",
    clinicName: "Sonawane Orthocare",
    specialty: "Orthopedics & Joint",
    city: "Pune",
    area: "Wakad",
    email: "dratulsonawane@gmail.com",
    phone: "+91 98902 44777",
    website: "https://dratulsonawane.com",
    sourceUrl: "https://dratulsonawane.com/contact/",
    verifiedObservation: "High walk-in joint replacement and fracture clinic in Wakad.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 5,
    doctorName: "Dr. Atul Bhaskar",
    clinicName: "Children's Orthopaedic Centre",
    specialty: "Pediatric Orthopedics",
    city: "Mumbai",
    area: "Bandra West",
    email: "arb_25@yahoo.com",
    phone: "+91 22 2640 1234",
    website: "https://childrenorthopaedic.com",
    sourceUrl: "https://childrenorthopaedic.com/contact-us/",
    verifiedObservation: "Dedicated pediatric orthopedic surgery and deformity correction centre in Bandra.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 6,
    doctorName: "Dr. Parag Sancheti",
    clinicName: "Sancheti Hospital OPD Centre",
    specialty: "Orthopedics & Joint",
    city: "Pune",
    area: "Shivajinagar",
    email: "appointment@sanchetihospital.org",
    phone: "+91 20 2899 9999",
    website: "https://sanchetihospital.org",
    sourceUrl: "https://sanchetihospital.org/contact-us/",
    verifiedObservation: "High throughput orthopedic outpatient consultation and rehabilitation in Shivajinagar.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 7,
    doctorName: "Dr. Narendra Vaidya",
    clinicName: "Lokmanya Orthopedics Hospital",
    specialty: "Orthopedics & Spine",
    city: "Pune",
    area: "Nigdi",
    email: "care@lokmanyahospitals.com",
    phone: "+91 20 6634 5678",
    website: "https://lokmanyahospitals.com",
    sourceUrl: "https://lokmanyahospitals.com/contact-us/",
    verifiedObservation: "Robotic joint replacement and trauma OPD handling large daily patient flow.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 8,
    doctorName: "Dr. P.K. Dave",
    clinicName: "Saroj Super Speciality Hospital OPD",
    specialty: "Orthopedics & Multi Specialty",
    city: "Delhi NCR",
    area: "Rohini",
    email: "info@sarojhospital.com",
    phone: "+91 11 4790 3333",
    website: "https://sarojhospital.com",
    sourceUrl: "https://sarojhospital.com/contact-us/",
    verifiedObservation: "Super speciality outpatient department with multi department walk-ins in Rohini.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 9,
    doctorName: "Dr. S. Gurushankar",
    clinicName: "Meenakshi Mission Hospital OPD",
    specialty: "Multi Specialty & Trauma",
    city: "Madurai",
    area: "Lake Area",
    email: "info@mmhrc.in",
    phone: "+91 452 426 3000",
    website: "https://mmhrc.in",
    sourceUrl: "https://mmhrc.in/contact-us/",
    verifiedObservation: "High volume daily outpatient intake handling multi specialty patient arrival waves.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 10,
    doctorName: "Dr. Balaji Sharma",
    clinicName: "Balaji Healthcare & Surgical Centre",
    specialty: "Surgical & Trauma",
    city: "Lucknow",
    area: "Alambagh",
    email: "helpdesk@balajihospitals.co.in",
    phone: "+91 522 245 6789",
    website: "https://balajihospitals.co.in",
    sourceUrl: "https://balajihospitals.co.in/contact/",
    verifiedObservation: "Surgical and trauma outpatient clinic with walk-in triage needs in Alambagh.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 11,
    doctorName: "Dr. Amitabha Roy",
    clinicName: "HealthFlex ENT & Head Neck Clinic",
    specialty: "ENT Care",
    city: "Kolkata",
    area: "Salt Lake",
    email: "info@entkolkata.co.in",
    phone: "+91 33 2334 5678",
    website: "https://entkolkata.co.in",
    sourceUrl: "https://entkolkata.co.in/contact/",
    verifiedObservation: "ENT outpatient practice with acute and routine consult mix in Salt Lake.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 12,
    doctorName: "Dr. Rajesh Garg",
    clinicName: "Garg Orthocare Centre",
    specialty: "Orthopedics",
    city: "Noida",
    area: "Sector 51",
    email: "info@gargorthocare.com",
    phone: "+91 120 456 7890",
    website: "https://gargorthocare.com",
    sourceUrl: "https://gargorthocare.com/contact/",
    verifiedObservation: "Orthopedic consultation and sports rehab clinic in Sector 51 Noida.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 13,
    doctorName: "Dr. Vivek Sharma",
    clinicName: "Sharma ENT & Head Neck Care",
    specialty: "ENT Care",
    city: "Delhi NCR",
    area: "Janakpuri",
    email: "info@sharmaentclinic.com",
    phone: "+91 11 2555 6789",
    website: "https://sharmaentclinic.com",
    sourceUrl: "https://sharmaentclinic.com/contact-us/",
    verifiedObservation: "Dedicated ear nose throat practice with high morning walk-in volume in Janakpuri.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 14,
    doctorName: "Dr. K. S. Reddy",
    clinicName: "KS Orthopedic Centre",
    specialty: "Orthopedics",
    city: "Chennai",
    area: "Anna Nagar",
    email: "contact@ksorthoclinic.in",
    phone: "+91 44 2621 3456",
    website: "https://ksorthoclinic.in",
    sourceUrl: "https://ksorthoclinic.in/contact/",
    verifiedObservation: "Joint restoration and spine OPD practice in Anna Nagar Chennai.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 15,
    doctorName: "Dr. A. K. Jain",
    clinicName: "Jain Joint & Spine Clinic",
    specialty: "Orthopedics",
    city: "Jaipur",
    area: "Malviya Nagar",
    email: "info@jainorthojp.com",
    phone: "+91 141 275 4321",
    website: "https://jainorthojp.com",
    sourceUrl: "https://jainorthojp.com/contact/",
    verifiedObservation: "Spine and joint replacement outpatient clinic in Malviya Nagar Jaipur.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 16,
    doctorName: "Dr. Nitish Saxena",
    clinicName: "Aster CMI Hospital OPD",
    specialty: "Multi Specialty OPD",
    city: "Bengaluru",
    area: "Hebbal",
    email: "info.astercmi@asterhospital.com",
    phone: "+91 80 4342 0100",
    website: "https://asterhospitals.in",
    sourceUrl: "https://asterhospitals.in/contact-us",
    verifiedObservation: "Large multi department outpatient facility with high morning patient check-in volume.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 17,
    doctorName: "Dr. S. K. Narang",
    clinicName: "Sterling Hospitals OPD",
    specialty: "Cardiology & Surgery",
    city: "Ahmedabad",
    area: "Gurukul",
    email: "info@sterlinghospitals.com",
    phone: "+91 79 4001 1111",
    website: "https://sterlinghospitals.com",
    sourceUrl: "https://sterlinghospitals.com/contact-us",
    verifiedObservation: "High throughput specialty outpatient consultations in Gurukul Ahmedabad.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 18,
    doctorName: "Dr. P. S. Venkatesh",
    clinicName: "Kovai Medical Center OPD",
    specialty: "Orthopedics & OPD",
    city: "Coimbatore",
    area: "Avinashi Road",
    email: "getwell@kmchhospitals.com",
    phone: "+91 422 432 3800",
    website: "https://kmchhospitals.com",
    sourceUrl: "https://kmchhospitals.com/contact-us",
    verifiedObservation: "Tertiary care outpatient center with multi specialty arrival streams.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 19,
    doctorName: "Dr. Anoop Misra",
    clinicName: "Fortis C-DOC Centre of Excellence",
    specialty: "Diabetes & Metabolic Care",
    city: "Delhi NCR",
    area: "Nehru Place",
    email: "contactus@fortiscdoc.com",
    phone: "+91 11 4910 1222",
    website: "https://fortiscdoc.com",
    sourceUrl: "https://fortiscdoc.com/contact/",
    verifiedObservation: "Specialized metabolic outpatient clinic with structured intake requirements.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 20,
    doctorName: "Dr. B. K. Rao",
    clinicName: "Sir Ganga Ram Hospital Critical OPD",
    specialty: "Internal Medicine",
    city: "Delhi NCR",
    area: "Rajinder Nagar",
    email: "criticalcare@sgrh.com",
    phone: "+91 11 2575 0000",
    website: "https://sgrh.com",
    sourceUrl: "https://sgrh.com/contact-us",
    verifiedObservation: "High daily patient footfall outpatient consultations in central Delhi.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 21,
    doctorName: "Dr. Vinod Raina",
    clinicName: "Fortis Memorial Specialty OPD",
    specialty: "Specialty Care",
    city: "Gurgaon",
    area: "Sector 44",
    email: "cancercare.fmri@fortishealthcare.com",
    phone: "+91 124 496 2200",
    website: "https://fortishealthcare.com",
    sourceUrl: "https://fortishealthcare.com/contact-us",
    verifiedObservation: "Super specialty clinic handling coordinated multi doctor outpatient queues.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 22,
    doctorName: "Dr. T. S. Kler",
    clinicName: "Fortis Escorts Heart OPD",
    specialty: "Cardiology",
    city: "Delhi NCR",
    area: "Okhla",
    email: "cardiology.fehi@fortishealthcare.com",
    phone: "+91 11 4713 5000",
    website: "https://fortishealthcare.com",
    sourceUrl: "https://fortishealthcare.com/locations/delhi/fortis-escorts-heart-institute",
    verifiedObservation: "High volume cardiac OPD where walk-in symptom triage is critical.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 23,
    doctorName: "Dr. Rajiv Parakh",
    clinicName: "Medanta Peripheral Vascular OPD",
    specialty: "Vascular Surgery",
    city: "Gurgaon",
    area: "Sector 38",
    email: "vascular@medanta.org",
    phone: "+91 124 414 1414",
    website: "https://medanta.org",
    sourceUrl: "https://medanta.org/doctors/dr-rajiv-parakh",
    verifiedObservation: "Vascular surgery and outpatient consult practice with arrival triage needs.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 24,
    doctorName: "Dr. Pradeep Sharma",
    clinicName: "Centre for Sight Strabismus OPD",
    specialty: "Ophthalmology",
    city: "Delhi NCR",
    area: "Safdarjung Enclave",
    email: "squint@centreforsight.net",
    phone: "+91 11 4266 6666",
    website: "https://centreforsight.net",
    sourceUrl: "https://centreforsight.net/contact-us",
    verifiedObservation: "Specialized eye outpatient practice with high consultation traffic.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },
  {
    rank: 25,
    doctorName: "Dr. Subash Kumar",
    clinicName: "Apollo Hospitals Greams Road OPD",
    specialty: "General Surgery & OPD",
    city: "Chennai",
    area: "Greams Road",
    email: "surgery.chennai@apollohospitals.com",
    phone: "+91 44 2829 0200",
    website: "https://apollohospitals.com",
    sourceUrl: "https://apollohospitals.com/locations/india/chennai/greams-road",
    verifiedObservation: "Major hospital outpatient consultation department with multi stream arrival queues.",
    campaignFamily: "CAMPAIGN_A_REGISTRATION_SOLVED"
  },

  // =========================================================================
  // CAMPAIGN B: AI Capacity & Intake Bottleneck (20 Prospects)
  // =========================================================================
  {
    rank: 26,
    doctorName: "Dr. Naresh Trehan",
    clinicName: "Medanta The Medicity OPD Hub",
    specialty: "Cardiology & Multi Specialty",
    city: "Gurgaon",
    area: "Sector 38",
    email: "info@medanta.org",
    phone: "+91 124 414 1414",
    website: "https://medanta.org",
    sourceUrl: "https://medanta.org/contact-us",
    verifiedObservation: "Flagship healthcare institute processing extensive daily outpatient registrations.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 27,
    doctorName: "Dr. Prathap C. Reddy",
    clinicName: "Apollo Hospitals Enterprise OPD",
    specialty: "Multi Specialty OPD",
    city: "Chennai",
    area: "Thousand Lights",
    email: "customercare@apollohospitals.com",
    phone: "+91 44 2829 3333",
    website: "https://apollohospitals.com",
    sourceUrl: "https://apollohospitals.com/contact-us",
    verifiedObservation: "Nationwide hospital chain evaluating AI and automated clinical workflow improvements.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 28,
    doctorName: "Dr. Devi Shetty",
    clinicName: "Narayana Health City OPD",
    specialty: "Cardiology & Multi Specialty",
    city: "Bengaluru",
    area: "Bommasandra",
    email: "info.nsh@narayanahealth.org",
    phone: "+91 80 7122 2222",
    website: "https://narayanahealth.org",
    sourceUrl: "https://narayanahealth.org/contact-us",
    verifiedObservation: "Leading technology-forward health network optimizing patient throughput and flow.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 29,
    doctorName: "Dr. Sudarshan Ballal",
    clinicName: "Manipal Hospitals Health Hub",
    specialty: "Internal Medicine & OPD",
    city: "Bengaluru",
    area: "Old Airport Road",
    email: "info@manipalhospitals.com",
    phone: "+91 80 2502 4444",
    website: "https://manipalhospitals.com",
    sourceUrl: "https://manipalhospitals.com/contact-us",
    verifiedObservation: "Multi branch hospital group streamlining reception and patient intake.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 30,
    doctorName: "Dr. Sandeep Budhiraja",
    clinicName: "Max Super Speciality Hospital",
    specialty: "Internal Medicine & Multi Specialty",
    city: "Delhi NCR",
    area: "Saket",
    email: "contactus@maxhealthcare.com",
    phone: "+91 11 2651 5050",
    website: "https://maxhealthcare.com",
    sourceUrl: "https://maxhealthcare.com/contact-us",
    verifiedObservation: "High throughput outpatient center managing multiple concurrent consulting rooms.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 31,
    doctorName: "Dr. Ashutosh Raghuvanshi",
    clinicName: "Fortis Healthcare Operations",
    specialty: "Multi Specialty",
    city: "Gurgaon",
    area: "Sector 44",
    email: "reachus@fortishealthcare.com",
    phone: "+91 124 496 2200",
    website: "https://fortishealthcare.com",
    sourceUrl: "https://fortishealthcare.com/contact-us",
    verifiedObservation: "National healthcare network focusing on digital outpatient efficiency and patient experience.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 32,
    doctorName: "Dr. B. S. Ajaikumar",
    clinicName: "HCG Specialty Care OPD",
    specialty: "Specialty Care",
    city: "Bengaluru",
    area: "K.R. Road",
    email: "info@hcgoncology.com",
    phone: "+91 80 4020 6000",
    website: "https://hcgoncology.com",
    sourceUrl: "https://hcgoncology.com/contact-us",
    verifiedObservation: "Specialized center requiring precision scheduling and prioritized arrival handling.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 33,
    doctorName: "Dr. Ramakanta Panda",
    clinicName: "Asian Heart Institute",
    specialty: "Cardiology & Surgery",
    city: "Mumbai",
    area: "BKC",
    email: "info@ahirc.com",
    phone: "+91 22 6698 6666",
    website: "https://asianheartinstitute.org",
    sourceUrl: "https://asianheartinstitute.org/contact-us",
    verifiedObservation: "High volume cardiac specialty hospital with urgent walk-in triage demands.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 34,
    doctorName: "Dr. Alok Sharma",
    clinicName: "NeuroGen Brain & Spine Institute",
    specialty: "Neurology & Spine",
    city: "Mumbai",
    area: "Navi Mumbai",
    email: "contact@neurogenbsi.com",
    phone: "+91 22 2778 3000",
    website: "https://neurogenbsi.com",
    sourceUrl: "https://neurogenbsi.com/contact-us",
    verifiedObservation: "Dedicated neurological institute with complex outpatient intake needs.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 35,
    doctorName: "Dr. Shuchin Bajaj",
    clinicName: "Ujala Cygnus Hospital",
    specialty: "Multi Specialty",
    city: "Lucknow",
    area: "Vikas Nagar",
    email: "info@ujalacygnus.com",
    phone: "+91 522 411 2233",
    website: "https://ujalacygnus.com",
    sourceUrl: "https://ujalacygnus.com/contact-us",
    verifiedObservation: "Multi specialty network bringing digitized healthcare to Tier 2 city outpatient clinics.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 36,
    doctorName: "Dr. R. K. Mani",
    clinicName: "Yashoda Super Speciality Hospital",
    specialty: "Pulmonology & OPD",
    city: "Ghaziabad",
    area: "Kaushambi",
    email: "info@yashodahospital.org",
    phone: "+91 120 418 2000",
    website: "https://yashodahospital.org",
    sourceUrl: "https://yashodahospital.org/contact-us",
    verifiedObservation: "High volume multi specialty hospital in NCR with heavy morning OPD walk-in rush.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 37,
    doctorName: "Dr. G. S. Rao",
    clinicName: "Yashoda Hospitals Somajiguda",
    specialty: "Multi Specialty OPD",
    city: "Hyderabad",
    area: "Somajiguda",
    email: "info@yashodamail.com",
    phone: "+91 40 4567 4567",
    website: "https://yashodahospitals.com",
    sourceUrl: "https://yashodahospitals.com/contact-us",
    verifiedObservation: "Major outpatient healthcare destination managing multiple specialist queues.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 38,
    doctorName: "Dr. K. Ravindranath",
    clinicName: "Gleneagles Global Hospitals",
    specialty: "Gastro & Surgery",
    city: "Hyderabad",
    area: "Lakdi-ka-pul",
    email: "info.hyderabad@globalhospitalsindia.com",
    phone: "+91 40 2324 4444",
    website: "https://gleneaglesglobalhospitals.com",
    sourceUrl: "https://gleneaglesglobalhospitals.com/contact-us",
    verifiedObservation: "Multi center outpatient practice optimizing digital queue scheduling.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 39,
    doctorName: "Dr. Somesh Mittal",
    clinicName: "Vikram Hospital Healthcare",
    specialty: "Cardiology & Surgery",
    city: "Bengaluru",
    area: "Millers Road",
    email: "care@vikramhospital.com",
    phone: "+91 80 7100 0000",
    website: "https://vikramhospital.com",
    sourceUrl: "https://vikramhospital.com/contact-us",
    verifiedObservation: "Central Bengaluru hospital with multi department outpatient intake.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 40,
    doctorName: "Dr. Subhash Chandra",
    clinicName: "BLK-Max Super Speciality Hospital",
    specialty: "Cardiology & OPD",
    city: "Delhi NCR",
    area: "Pusa Road",
    email: "info@blkhospital.com",
    phone: "+91 11 3040 3040",
    website: "https://blkmaxhospital.com",
    sourceUrl: "https://blkmaxhospital.com/contact-us",
    verifiedObservation: "High density outpatient clinic handling hundreds of daily walk-in consultations.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 41,
    doctorName: "Dr. Nandkishore Kapadia",
    clinicName: "Kokilaben Dhirubhai Ambani Hospital",
    specialty: "Multi Specialty OPD",
    city: "Mumbai",
    area: "Andheri West",
    email: "info@kdahospital.org",
    phone: "+91 22 4269 6969",
    website: "https://kokilabenhospital.com",
    sourceUrl: "https://kokilabenhospital.com/contact-us",
    verifiedObservation: "Large multi specialty hospital optimizing OPD queue and reception flow.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 42,
    doctorName: "Dr. P. C. Rath",
    clinicName: "Apollo Hospitals Jubilee Hills",
    specialty: "Cardiology",
    city: "Hyderabad",
    area: "Jubilee Hills",
    email: "apollo_hyderabad@apollohospitals.com",
    phone: "+91 40 2360 7777",
    website: "https://apollohospitals.com",
    sourceUrl: "https://apollohospitals.com/locations/india/hyderabad/jubilee-hills",
    verifiedObservation: "Prominent cardiology and multi specialty outpatient center in Hyderabad.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 43,
    doctorName: "Dr. Amit Varma",
    clinicName: "Paras Healthcare OPD",
    specialty: "Multi Specialty",
    city: "Gurgaon",
    area: "Sector 43",
    email: "contact@parashospitals.com",
    phone: "+91 124 458 5555",
    website: "https://parashospitals.com",
    sourceUrl: "https://parashospitals.com/contact-us",
    verifiedObservation: "Regional hospital network modernizing outpatient intake workflows.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 44,
    doctorName: "Dr. Dharmesh Kapoor",
    clinicName: "Care Hospitals Banjara Hills",
    specialty: "Multi Specialty & Liver",
    city: "Hyderabad",
    area: "Banjara Hills",
    email: "info@carehospitals.com",
    phone: "+91 40 6165 6565",
    website: "https://carehospitals.com",
    sourceUrl: "https://carehospitals.com/contact-us",
    verifiedObservation: "Multi specialty hospital department balancing scheduled and walk-in arrivals.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },
  {
    rank: 45,
    doctorName: "Dr. Sunil K. Pandya",
    clinicName: "Jaslok Hospital OPD Services",
    specialty: "Multi Specialty",
    city: "Mumbai",
    area: "Pedder Road",
    email: "info@jaslokhospital.net",
    phone: "+91 22 6657 3333",
    website: "https://jaslokhospital.net",
    sourceUrl: "https://jaslokhospital.net/contact-us",
    verifiedObservation: "Established Mumbai healthcare institution with high volume daily OPD consulting.",
    campaignFamily: "CAMPAIGN_B_AI_CAPACITY"
  },

  // =========================================================================
  // CAMPAIGN C: Small Clinic Digitization (15 Prospects)
  // =========================================================================
  {
    rank: 46,
    doctorName: "Dr. Manish Khanna",
    clinicName: "Apley Orthopaedic Centre",
    specialty: "Orthopedics",
    city: "Lucknow",
    area: "Gomti Nagar",
    email: "apleyortho@gmail.com",
    phone: "+91 522 400 1234",
    website: "https://apleyorthocentre.com",
    sourceUrl: "https://apleyorthocentre.com/contact-us/",
    verifiedObservation: "Independent orthopedic practice handling high walk-in joint pain consultations in Gomti Nagar.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 47,
    doctorName: "Dr. Rohit Chakor",
    clinicName: "Bone & Joint Clinic",
    specialty: "Orthopedics",
    city: "Pune",
    area: "Baner",
    email: "drrohitchakor@gmail.com",
    phone: "+91 98231 45678",
    website: "https://boneandjointclinic.in",
    sourceUrl: "https://boneandjointclinic.in/contact/",
    verifiedObservation: "Private orthopedic outpatient clinic in Baner with solo practitioner queue management.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 48,
    doctorName: "Dr. Nikhil Sharma",
    clinicName: "Ace Orthocare",
    specialty: "Orthopedics & Trauma",
    city: "Gurgaon",
    area: "Sector 51",
    email: "contact@aceorthocare.com",
    phone: "+91 124 422 3344",
    website: "https://aceorthocare.com",
    sourceUrl: "https://aceorthocare.com/contact/",
    verifiedObservation: "Independent orthopedic and sports injury outpatient practice in Gurgaon.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 49,
    doctorName: "Dr. Chakradhar Reddy",
    clinicName: "Dr. Chakri's Ortho Clinic",
    specialty: "Orthopedics",
    city: "Hyderabad",
    area: "Kukatpally",
    email: "info@drchakrisortho.com",
    phone: "+91 40 2306 7890",
    website: "https://drchakrisortho.com",
    sourceUrl: "https://drchakrisortho.com/contact/",
    verifiedObservation: "Private orthopedic practice managing heavy walk-in queue in Kukatpally.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 50,
    doctorName: "Dr. Vikas Gupta",
    clinicName: "Hand & Upper Extremity Clinic",
    specialty: "Orthopedics",
    city: "Delhi NCR",
    area: "Lajpat Nagar",
    email: "info@drvikasgupta.com",
    phone: "+91 11 4172 8899",
    website: "https://drvikasgupta.com",
    sourceUrl: "https://drvikasgupta.com/contact/",
    verifiedObservation: "Specialized upper extremity outpatient practice in South Delhi.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 51,
    doctorName: "Dr. Rajesh Verma",
    clinicName: "Spine & Bone Care",
    specialty: "Orthopedics & Spine",
    city: "Noida",
    area: "Sector 62",
    email: "drrajeshverma@spinecare.in",
    phone: "+91 120 240 1234",
    website: "https://drrajeshvermaspine.com",
    sourceUrl: "https://drrajeshvermaspine.com/contact/",
    verifiedObservation: "Private spine outpatient consultation clinic in Sector 62 Noida.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 52,
    doctorName: "Dr. Ananya Mukherjee",
    clinicName: "Care & Cure ENT Centre",
    specialty: "ENT & Head Neck",
    city: "Kolkata",
    area: "Salt Lake",
    email: "carecureent@gmail.com",
    phone: "+91 33 2358 1122",
    website: "https://carecureentclinic.com",
    sourceUrl: "https://carecureentclinic.com/contact-us/",
    verifiedObservation: "Small independent ENT clinic with busy morning walk-in OPD in Salt Lake.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 53,
    doctorName: "Dr. Tarun Grover",
    clinicName: "Vascular & Vein Clinic",
    specialty: "Vascular Surgery",
    city: "Delhi NCR",
    area: "Vasant Kunj",
    email: "info@tarungrover.com",
    phone: "+91 11 2612 3456",
    website: "https://tarungrover.com",
    sourceUrl: "https://tarungrover.com/contact/",
    verifiedObservation: "Specialized outpatient clinic handling vascular consultations.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 54,
    doctorName: "Dr. Vishal Patil",
    clinicName: "Dr. Vishal Patil Ortho Clinic",
    specialty: "Orthopedics",
    city: "Pune",
    area: "Kothrud",
    email: "drvishalarthrocare@gmail.com",
    phone: "+91 98224 55667",
    website: "https://drvishalpatil.com",
    sourceUrl: "https://drvishalpatil.com/contact/",
    verifiedObservation: "Independent orthopedic practice serving Kothrud residential patients.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 55,
    doctorName: "Dr. Mahesh Kulkarni",
    clinicName: "Joint Replacement Clinic Pune",
    specialty: "Orthopedics",
    city: "Pune",
    area: "Deccan",
    email: "jointreplacementpune@gmail.com",
    phone: "+91 20 2553 1122",
    website: "https://jointreplacementpune.com",
    sourceUrl: "https://jointreplacementpune.com/contact/",
    verifiedObservation: "Private orthopedic practice managing appointment and walk-in mix.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 56,
    doctorName: "Dr. Aniket Patil",
    clinicName: "Om Ortho & Physio Clinic",
    specialty: "Orthopedics & Physio",
    city: "Pune",
    area: "Hadapsar",
    email: "draniketpatil12@gmail.com",
    phone: "+91 98901 22334",
    website: "https://omorthoclinic.com",
    sourceUrl: "https://omorthoclinic.com/contact/",
    verifiedObservation: "Combined orthopedic and physiotherapy outpatient clinic in Hadapsar.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 57,
    doctorName: "Dr. Alok Verma",
    clinicName: "Verma Ortho & Trauma Clinic",
    specialty: "Orthopedics",
    city: "Lucknow",
    area: "Indira Nagar",
    email: "alokortholko@gmail.com",
    phone: "+91 522 234 5678",
    website: "https://vermaorthoclinic.com",
    sourceUrl: "https://vermaorthoclinic.com/contact/",
    verifiedObservation: "Community orthopedic practice handling acute sprains and chronic joint consultations.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 58,
    doctorName: "Dr. Sanjay Bhatnagar",
    clinicName: "Bhatnagar Orthocenter",
    specialty: "Orthopedics",
    city: "Noida",
    area: "Sector 29",
    email: "bhatnagarorthonoida@gmail.com",
    phone: "+91 120 422 5566",
    website: "https://bhatnagarortho.com",
    sourceUrl: "https://bhatnagarortho.com/contact/",
    verifiedObservation: "Private orthopedic clinic in Noida Sector 29.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 59,
    doctorName: "Dr. Tarun Kumar",
    clinicName: "Kumar Orthopedic & Spine Clinic",
    specialty: "Orthopedics",
    city: "Hyderabad",
    area: "Madhapur",
    email: "kumarorthohyd@gmail.com",
    phone: "+91 40 4011 2233",
    website: "https://kumarorthoclinic.com",
    sourceUrl: "https://kumarorthoclinic.com/contact/",
    verifiedObservation: "Independent orthopedic practice in IT corridor Madhapur.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },
  {
    rank: 60,
    doctorName: "Dr. Sunil Deshmukh",
    clinicName: "Deshmukh Polyclinic",
    specialty: "General Medicine & Multi",
    city: "Pune",
    area: "Sinhagad Road",
    email: "deshmukhpolyclinic@gmail.com",
    phone: "+91 20 2434 5678",
    website: "https://deshmukhpolyclinic.com",
    sourceUrl: "https://deshmukhpolyclinic.com/contact/",
    verifiedObservation: "High footfall neighborhood polyclinic with multi doctor evening consultations.",
    campaignFamily: "CAMPAIGN_C_SMALL_CLINIC_DIGITIZATION"
  },

  // =========================================================================
  // CAMPAIGN D: Specialty-Specific Queue Asymmetry (20 Prospects)
  // =========================================================================
  {
    rank: 61,
    doctorName: "Dr. K. Sai Eswar",
    clinicName: "Sai Eswar Children's Clinic",
    specialty: "Pediatrics",
    city: "Chennai",
    area: "Anna Nagar",
    email: "saieswarkids@gmail.com",
    phone: "+91 44 2626 7890",
    website: "https://saieswarkids.com",
    sourceUrl: "https://saieswarkids.com/contact/",
    verifiedObservation: "Dedicated pediatric outpatient clinic where acute fever cases wait alongside routine checkups.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 62,
    doctorName: "Dr. Smita Prasad",
    clinicName: "Little Feet Child Clinic",
    specialty: "Pediatrics",
    city: "Bengaluru",
    area: "Indiranagar",
    email: "littlefeetblr@gmail.com",
    phone: "+91 80 2520 1122",
    website: "https://littlefeetchildclinic.in",
    sourceUrl: "https://littlefeetchildclinic.in/contact/",
    verifiedObservation: "Busy pediatric OPD managing high morning walk-in volume of infants and children.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 63,
    doctorName: "Dr. Sunita Rao",
    clinicName: "Mother & Child Care Clinic",
    specialty: "Pediatrics",
    city: "Bengaluru",
    area: "Jayanagar",
    email: "care@motherandchildblr.com",
    phone: "+91 80 2663 4455",
    website: "https://motherandchildblr.com",
    sourceUrl: "https://motherandchildblr.com/contact/",
    verifiedObservation: "Pediatric care center balancing vaccination queues with acute sick child walk-ins.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 64,
    doctorName: "Dr. Pallavi Joshi",
    clinicName: "Joshi Children's Clinic",
    specialty: "Pediatrics",
    city: "Pune",
    area: "Kothrud",
    email: "joshichildrensclinic@gmail.com",
    phone: "+91 20 2544 3322",
    website: "https://joshichildrensclinic.com",
    sourceUrl: "https://joshichildrensclinic.com/contact/",
    verifiedObservation: "High density pediatric OPD practice in Kothrud Pune.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 65,
    doctorName: "Dr. Radhika Menon",
    clinicName: "Menon Pediatric Centre",
    specialty: "Pediatrics",
    city: "Chennai",
    area: "Adyar",
    email: "menonchildcare@gmail.com",
    phone: "+91 44 2441 5566",
    website: "https://menonchildcare.com",
    sourceUrl: "https://menonchildcare.com/contact/",
    verifiedObservation: "Pediatric outpatient clinic with infant immunization and acute walk-in queues.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 66,
    doctorName: "Dr. Priya Das",
    clinicName: "Das Child Health Clinic",
    specialty: "Pediatrics",
    city: "Kolkata",
    area: "Alipore",
    email: "daschildclinic@gmail.com",
    phone: "+91 33 2479 2233",
    website: "https://daschildclinic.com",
    sourceUrl: "https://daschildclinic.com/contact/",
    verifiedObservation: "Pediatric consultation clinic in South Kolkata handling daily sick child arrivals.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 67,
    doctorName: "Dr. Swati Ghosh",
    clinicName: "Ghosh Pediatric & Newborn Clinic",
    specialty: "Pediatrics",
    city: "Kolkata",
    area: "Salt Lake",
    email: "ghoshchildcare@gmail.com",
    phone: "+91 33 2321 4455",
    website: "https://ghoshchildclinic.com",
    sourceUrl: "https://ghoshchildclinic.com/contact/",
    verifiedObservation: "Newborn and pediatric clinic managing urgent fever vs routine developmental checks.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 68,
    doctorName: "Dr. Deepali Mishra",
    clinicName: "Mishra Child & Vaccination Care",
    specialty: "Pediatrics",
    city: "Lucknow",
    area: "Mahanagar",
    email: "mishrachildcarelko@gmail.com",
    phone: "+91 522 232 1122",
    website: "https://mishrachildcare.com",
    sourceUrl: "https://mishrachildcare.com/contact/",
    verifiedObservation: "Pediatric OPD in Mahanagar balancing scheduled shots with unscheduled high fever walk-ins.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 69,
    doctorName: "Dr. Arvind Kulkarni",
    clinicName: "Spine & Joint Health Centre",
    specialty: "Orthopedics & Spine",
    city: "Mumbai",
    area: "Bandra",
    email: "spinehealthmumbai@gmail.com",
    phone: "+91 22 2642 7788",
    website: "https://spinehealthmumbai.com",
    sourceUrl: "https://spinehealthmumbai.com/contact/",
    verifiedObservation: "Spine OPD clinic where post-op reviews and acute nerve compression walk-ins share the queue.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 70,
    doctorName: "Dr. Neeraj Bansal",
    clinicName: "Bansal Orthopedic & Spine Centre",
    specialty: "Orthopedics",
    city: "Delhi NCR",
    area: "Pitampura",
    email: "bansalorthodelhi@gmail.com",
    phone: "+91 11 2734 5566",
    website: "https://bansalorthoclinic.com",
    sourceUrl: "https://bansalorthoclinic.com/contact/",
    verifiedObservation: "Orthopedic surgery and trauma OPD practice in North Delhi.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 71,
    doctorName: "Dr. Anand Rao",
    clinicName: "Rao Orthopedic & Sports Clinic",
    specialty: "Orthopedics",
    city: "Bengaluru",
    area: "Koramangala",
    email: "raoorthoblr@gmail.com",
    phone: "+91 80 2552 3344",
    website: "https://raoorthoclinic.com",
    sourceUrl: "https://raoorthoclinic.com/contact/",
    verifiedObservation: "Sports injury clinic where fresh joint sprains wait alongside routine follow-ups.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 72,
    doctorName: "Dr. Vinod Sharma",
    clinicName: "Sharma Ortho & Joint Clinic",
    specialty: "Orthopedics",
    city: "Jaipur",
    area: "C Scheme",
    email: "sharmaorthojaipur@gmail.com",
    phone: "+91 141 237 8899",
    website: "https://sharmaorthojaipur.com",
    sourceUrl: "https://sharmaorthojaipur.com/contact/",
    verifiedObservation: "Orthopedic practice in central Jaipur managing mixed acute trauma and chronic arthritis patients.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 73,
    doctorName: "Dr. Saurabh Jain",
    clinicName: "Jain Spine & Orthocare",
    specialty: "Orthopedics & Spine",
    city: "Lucknow",
    area: "Hazratganj",
    email: "jainspineortho@gmail.com",
    phone: "+91 522 228 9900",
    website: "https://jainspineortho.com",
    sourceUrl: "https://jainspineortho.com/contact/",
    verifiedObservation: "Spine and joint clinic with heavy walk-in queue in central Lucknow.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 74,
    doctorName: "Dr. Deepa Sen",
    clinicName: "Sen Skin & Aesthetics",
    specialty: "Dermatology",
    city: "Kolkata",
    area: "Park Street",
    email: "senskinclinic@gmail.com",
    phone: "+91 33 2229 4455",
    website: "https://senskinclinic.com",
    sourceUrl: "https://senskinclinic.com/contact/",
    verifiedObservation: "Dermatology practice where acute allergy flare-ups and routine cosmetic consults share the queue.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 75,
    doctorName: "Dr. Amit Gupta",
    clinicName: "Gupta Skin & Laser Clinic",
    specialty: "Dermatology",
    city: "Delhi NCR",
    area: "Greater Kailash",
    email: "guptaskindelhi@gmail.com",
    phone: "+91 11 2923 7788",
    website: "https://guptaskindelhi.com",
    sourceUrl: "https://guptaskindelhi.com/contact/",
    verifiedObservation: "Clinical and aesthetic dermatology OPD in South Delhi.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 76,
    doctorName: "Dr. Shalini Kulkarni",
    clinicName: "Kulkarni Skin & Hair Care",
    specialty: "Dermatology",
    city: "Pune",
    area: "Aundh",
    email: "kulkarniskinpune@gmail.com",
    phone: "+91 20 2588 4455",
    website: "https://kulkarniskinpune.com",
    sourceUrl: "https://kulkarniskinpune.com/contact/",
    verifiedObservation: "Dermatology clinic with procedural treatments and acute skin consultations.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 77,
    doctorName: "Dr. Poonam Sethi",
    clinicName: "Sethi Skin & Aesthetic Centre",
    specialty: "Dermatology",
    city: "Delhi NCR",
    area: "Hauz Khas",
    email: "sethiskindelhi@gmail.com",
    phone: "+91 11 2656 1122",
    website: "https://sethiskindelhi.com",
    sourceUrl: "https://sethiskindelhi.com/contact/",
    verifiedObservation: "Cosmetology and clinical skin clinic managing walk-in patient flow in Hauz Khas.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 78,
    doctorName: "Dr. Maya Hegde",
    clinicName: "Hegde Skin & Aesthetic Centre",
    specialty: "Dermatology",
    city: "Bengaluru",
    area: "Malleshwaram",
    email: "hegdeskinblr@gmail.com",
    phone: "+91 80 2334 8899",
    website: "https://hegdeskincentre.com",
    sourceUrl: "https://hegdeskincentre.com/contact/",
    verifiedObservation: "Clinical dermatology center in Malleshwaram.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 79,
    doctorName: "Dr. Meenakshi Sundaram",
    clinicName: "Sundaram Eye & Retina Care",
    specialty: "Ophthalmology",
    city: "Chennai",
    area: "T Nagar",
    email: "sundarameye@gmail.com",
    phone: "+91 44 2815 3344",
    website: "https://sundarameyecare.com",
    sourceUrl: "https://sundarameyecare.com/contact/",
    verifiedObservation: "Eye clinic where acute corneal foreign bodies and routine refractive checks share reception.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },
  {
    rank: 80,
    doctorName: "Dr. Rohit Saxena",
    clinicName: "Saxena Eye & Laser Centre",
    specialty: "Ophthalmology",
    city: "Lucknow",
    area: "Gomti Nagar",
    email: "saxenaeyelko@gmail.com",
    phone: "+91 522 404 5566",
    website: "https://saxenaeyecentre.com",
    sourceUrl: "https://saxenaeyecentre.com/contact/",
    verifiedObservation: "Ophthalmology clinic in Gomti Nagar managing cataract, refractive and emergency eye walk-ins.",
    campaignFamily: "CAMPAIGN_D_SPECIALTY_ASYMMETRY"
  },

  // =========================================================================
  // CAMPAIGN E: The Human Receptionist Dilemma (20 Prospects)
  // =========================================================================
  {
    rank: 81,
    doctorName: "Dr. Surendra Singh",
    clinicName: "Singh ENT Clinic",
    specialty: "ENT Care",
    city: "Jaipur",
    area: "Raja Park",
    email: "singhentjaipur@gmail.com",
    phone: "+91 141 262 3344",
    website: "https://singhentjaipur.com",
    sourceUrl: "https://singhentjaipur.com/contact/",
    verifiedObservation: "High walk-in ENT clinic where receptionists manage acute ear pain and voice consultations.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 82,
    doctorName: "Dr. Prateek Srivastava",
    clinicName: "Srivastava ENT & Sinus Centre",
    specialty: "ENT Care",
    city: "Lucknow",
    area: "Alambagh",
    email: "srivastavaentlko@gmail.com",
    phone: "+91 522 245 1122",
    website: "https://srivastavaent.com",
    sourceUrl: "https://srivastavaent.com/contact/",
    verifiedObservation: "Busy ENT practice where front-desk staff must decide priority without clinical diagnostic tools.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 83,
    doctorName: "Dr. Karthik Sundar",
    clinicName: "Sundar ENT Care Centre",
    specialty: "ENT Care",
    city: "Chennai",
    area: "Mylapore",
    email: "sundarentchennai@gmail.com",
    phone: "+91 44 2498 7788",
    website: "https://sundarentclinic.com",
    sourceUrl: "https://sundarentclinic.com/contact/",
    verifiedObservation: "ENT outpatient clinic in Mylapore handling heavy morning patient arrivals.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 84,
    doctorName: "Dr. Murali Mohan",
    clinicName: "Mohan ENT & Voice Clinic",
    specialty: "ENT Care",
    city: "Hyderabad",
    area: "Secunderabad",
    email: "mohanenthyd@gmail.com",
    phone: "+91 40 2780 4455",
    website: "https://mohanentclinic.com",
    sourceUrl: "https://mohanentclinic.com/contact/",
    verifiedObservation: "Voice and ear clinic with high daily reception traffic.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 85,
    doctorName: "Dr. Arun Kumar",
    clinicName: "Kumar ENT & Allergy Clinic",
    specialty: "ENT Care",
    city: "Noida",
    area: "Sector 27",
    email: "kumarentnoida@gmail.com",
    phone: "+91 120 433 8899",
    website: "https://kumarentnoida.com",
    sourceUrl: "https://kumarentnoida.com/contact/",
    verifiedObservation: "ENT and allergy practice where front desk balances appointment tokens with urgent walk-ins.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 86,
    doctorName: "Dr. R.V. Raman",
    clinicName: "Raman Heart & Vascular Clinic",
    specialty: "Cardiology",
    city: "Chennai",
    area: "Kilpauk",
    email: "ramanheartcare@gmail.com",
    phone: "+91 44 2644 1122",
    website: "https://ramanheartcare.com",
    sourceUrl: "https://ramanheartcare.com/contact/",
    verifiedObservation: "Cardiology OPD where reception staff must catch subtle discomfort red flags before the doctor consult.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 87,
    doctorName: "Dr. Harish Chandra",
    clinicName: "Chandra Heart & Chest Clinic",
    specialty: "Cardiology",
    city: "Lucknow",
    area: "Alambagh",
    email: "chandraheartlko@gmail.com",
    phone: "+91 522 245 9900",
    website: "https://chandraheartclinic.com",
    sourceUrl: "https://chandraheartclinic.com/contact/",
    verifiedObservation: "Heart and chest outpatient clinic where walk-in triage accuracy is paramount.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 88,
    doctorName: "Dr. Manish Tandon",
    clinicName: "Tandon Gastro & Liver Clinic",
    specialty: "Gastroenterology",
    city: "Lucknow",
    area: "Indira Nagar",
    email: "tandongastrolko@gmail.com",
    phone: "+91 522 235 4455",
    website: "https://tandongastroclinic.com",
    sourceUrl: "https://tandongastroclinic.com/contact/",
    verifiedObservation: "Gastroenterology practice handling acute abdominal pain walk-ins amidst routine consultations.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 89,
    doctorName: "Dr. Hemant Patel",
    clinicName: "Patel Dental & Maxillofacial",
    specialty: "Dentistry",
    city: "Ahmedabad",
    area: "Navrangpura",
    email: "pateldentalcare@gmail.com",
    phone: "+91 79 2644 5566",
    website: "https://pateldentalcare.com",
    sourceUrl: "https://pateldentalcare.com/contact/",
    verifiedObservation: "Dental and maxillofacial surgery OPD handling acute trauma and toothache walk-ins.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 90,
    doctorName: "Dr. Ajay Mehta",
    clinicName: "Mehta Dental Care & Implantology",
    specialty: "Dentistry",
    city: "Mumbai",
    area: "Juhu",
    email: "mehtadentaljuhu@gmail.com",
    phone: "+91 22 2618 3344",
    website: "https://mehtadentalcare.com",
    sourceUrl: "https://mehtadentalcare.com/contact/",
    verifiedObservation: "Dental clinic balancing scheduled long procedures with emergency walk-in patients.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 91,
    doctorName: "Dr. Sandip Mukherjee",
    clinicName: "Mukherjee Dental Surgery",
    specialty: "Dentistry",
    city: "Kolkata",
    area: "Ballygunge",
    email: "mukherjeedentalcare@gmail.com",
    phone: "+91 33 2464 1122",
    website: "https://mukherjeedental.com",
    sourceUrl: "https://mukherjeedental.com/contact/",
    verifiedObservation: "Dental practice where reception manages appointment books alongside unscheduled acute pain walk-ins.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 92,
    doctorName: "Dr. Geeta Nair",
    clinicName: "Nair Women's Clinic",
    specialty: "Gynecology",
    city: "Bengaluru",
    area: "Indiranagar",
    email: "nairwomenscare@gmail.com",
    phone: "+91 80 2521 6677",
    website: "https://nairwomensclinic.com",
    sourceUrl: "https://nairwomensclinic.com/contact/",
    verifiedObservation: "Women's healthcare clinic where urgent antenatal complaints share reception with routine checkups.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 93,
    doctorName: "Dr. Kavita Reddy",
    clinicName: "Reddy Women's Care & Maternity",
    specialty: "Gynecology",
    city: "Hyderabad",
    area: "Banjara Hills",
    email: "reddywomenshyd@gmail.com",
    phone: "+91 40 2335 8899",
    website: "https://reddywomenscare.com",
    sourceUrl: "https://reddywomenscare.com/contact/",
    verifiedObservation: "Maternity and gynecology practice handling walk-in priority decisions at reception.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 94,
    doctorName: "Dr. Ritu Agarwal",
    clinicName: "Agarwal Gynae & Fertility Clinic",
    specialty: "Gynecology",
    city: "Jaipur",
    area: "Vaishali Nagar",
    email: "agarwalgynaejaipur@gmail.com",
    phone: "+91 141 235 4455",
    website: "https://agarwalgynaeclinic.com",
    sourceUrl: "https://agarwalgynaeclinic.com/contact/",
    verifiedObservation: "Gynecology and fertility OPD managing arrival order and emergency consultation requests.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 95,
    doctorName: "Dr. Rashmi Patel",
    clinicName: "Patel Women's Clinic",
    specialty: "Gynecology",
    city: "Ahmedabad",
    area: "Satellite",
    email: "patelwomensclinic@gmail.com",
    phone: "+91 79 2676 1122",
    website: "https://patelwomenscare.com",
    sourceUrl: "https://patelwomenscare.com/contact/",
    verifiedObservation: "Women's health clinic in Satellite Ahmedabad.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 96,
    doctorName: "Dr. Archana Balan",
    clinicName: "Balan Eye Care Clinic",
    specialty: "Ophthalmology",
    city: "Chennai",
    area: "Mylapore",
    email: "balaneyecare@gmail.com",
    phone: "+91 44 2499 3344",
    website: "https://balaneyecare.com",
    sourceUrl: "https://balaneyecare.com/contact/",
    verifiedObservation: "Eye clinic where receptionists handle acute eye trauma, redness and routine vision tests.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 97,
    doctorName: "Dr. Ananya Roy",
    clinicName: "Roy Eye Clinic & Vision Therapy",
    specialty: "Ophthalmology",
    city: "Kolkata",
    area: "Salt Lake",
    email: "royeyeclinic@gmail.com",
    phone: "+91 33 2337 5566",
    website: "https://royeyeclinic.com",
    sourceUrl: "https://royeyeclinic.com/contact/",
    verifiedObservation: "Vision and eye clinic in Salt Lake.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 98,
    doctorName: "Dr. Vikram Seth",
    clinicName: "Seth Orthopaedic & Joint Clinic",
    specialty: "Orthopedics",
    city: "Gurgaon",
    area: "Sector 49",
    email: "sethorthogurgaon@gmail.com",
    phone: "+91 124 405 6677",
    website: "https://sethorthoclinic.com",
    sourceUrl: "https://sethorthoclinic.com/contact/",
    verifiedObservation: "Joint and spine clinic where front desk balances appointment tokens with walk-ins.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 99,
    doctorName: "Dr. Manish Kapoor",
    clinicName: "Kapoor Heart & Medical Polyclinic",
    specialty: "Multi Specialty & Cardiology",
    city: "Delhi NCR",
    area: "Janakpuri",
    email: "kapoorpolyclinicdelhi@gmail.com",
    phone: "+91 11 2550 4455",
    website: "https://kapoorpolyclinic.in",
    sourceUrl: "https://kapoorpolyclinic.in/contact/",
    verifiedObservation: "Multi doctor polyclinic where reception manages arrival sequence across consulting rooms.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  },
  {
    rank: 100,
    doctorName: "Dr. Aniruddh Joshi",
    clinicName: "Joshi Orthopaedic & Trauma Centre",
    specialty: "Orthopedics & Trauma",
    city: "Pune",
    area: "Pashan",
    email: "joshiarthrocare@gmail.com",
    phone: "+91 20 2587 1122",
    website: "https://joshiarthrocare.com",
    sourceUrl: "https://joshiarthrocare.com/contact/",
    verifiedObservation: "Joint restoration and acute trauma practice in Pashan Pune with heavy walk-in queue.",
    campaignFamily: "CAMPAIGN_E_RECEPTIONIST_DILEMMA"
  }
];

export function getAllProspectLeads(): ProspectLead[] {
  return MASTER_100_PROSPECTS.map(clinic => {
    const subjectVariants = generateSubjectVariants(
      clinic.campaignFamily,
      clinic.doctorName,
      clinic.clinicName,
      clinic.specialty
    );

    const emailContent = generateCampaignEmail({
      doctorName: clinic.doctorName,
      clinicName: clinic.clinicName,
      specialty: clinic.specialty,
      city: clinic.city,
      campaignFamily: clinic.campaignFamily,
      verifiedObservation: clinic.verifiedObservation
    });

    return {
      rank: clinic.rank,
      doctorName: clinic.doctorName,
      clinicName: clinic.clinicName,
      specialty: clinic.specialty,
      city: clinic.city,
      area: clinic.area,
      email: clinic.email,
      phone: clinic.phone,
      website: clinic.website,
      sourceUrl: clinic.sourceUrl,
      verifiedAt: "2026-09-03",
      verificationMethod: "Public Clinic Domain & Official Contact Page",
      verificationStatus: 'VERIFIED',
      verifiedObservation: clinic.verifiedObservation,
      campaignAngle: clinic.campaignFamily,
      subjectVariants: {
        A: subjectVariants.A,
        B: subjectVariants.B,
        C: subjectVariants.C
      },
      selectedSubject: emailContent.subject,
      emailBody: emailContent.plainText,
      plainTextBody: emailContent.plainText,
      htmlBody: emailContent.html,
      status: 'QUEUED'
    };
  });
}
